# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TinyApiClientExample' do
  use_frameworks!

  pod 'TinyAPIClient', :path => '../'

  target 'TinyApiClientExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TinyApiClientExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
